### ISSUE TITLE
Remove `devices`

### ISSUE THREAD

**Issue by hrueger** [node-dmx/dmx-ts#1]
@Granjow what about removing the `devices` part (https://github.com/node-dmx/dmx-ts#dmxdevices)? As far as I can see, they are not used anywhere. Instead, we could point people to the [OpenFixtureLibrary](https://open-fixture-library.org/).

**Comment by JonahKr** [comment]
First of all, I reviewed  one of your PRs (OFL) @hrueger and i actually remember it to be one of only perfect ones I have seen so far. 😂 
I think basic support for devices should still be available because the very extensive Schemas which OFL provides are somewhat overkill for a normal user/tinkerer.

I think however that it could be made easier to use OFL by adapting their Schema with some custom import/exports for a simplified version.

**Comment by hrueger** [comment]
Makes sense, I completely agree with you 👍
